### ISSUE TITLE
Aim wobble increases on higher resolutions

### ISSUE THREAD

**Issue by RogueRaiden** [Rahjital/VSBullseye#8]
A user brought something rather important to my attention. Seems the aim wobble gets much more wild with higher resolution monitors. He has a 2160p and 1080p display. On the 1080p, the wobble is rather slow and within a small area. When he moves to 4K, the wobble speeds up a lot and covers a much larger area. I personally play on 1440p and didnt think it was that bad but the difference i saw was rather huge.

**Comment by TeacupAngel** [comment]
Tested the difference on 2160p, 1080p, and 540p. The wobble does speed up on higher resolutions, but the reticle moves the same distance and there seems to be no difference in accuracy between 128 arrows shot on each display resolution. It seems to be just an illusion caused by the reticle texture getting smaller on higher resolutions, which makes the reticle travel farther compared to its own size.

Current plan is to introduce scaling on the crosshair texture to keep it more consistent across resolutions, with the option to disable it clientside if wanted.

**Comment by TeacupAngel** [comment]
2.5.0-rc.2 will release soon with optional (on by default) scaling of the reticle based on the UI scale you pick in the settings. That should hopefully make playing at 4k and similar resolutions more enjoyable :)
